# Generated by Django 4.2.5 on 2023-09-08 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='dname',
        ),
        migrations.RemoveField(
            model_name='district',
            name='dname',
        ),
        migrations.AddField(
            model_name='branch',
            name='name',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='district',
            name='name',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(max_length=8)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('phonenumber', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('S', 'Saving Account'), ('C', 'Current Account')], max_length=1)),
                ('materials_provided', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bankapp.branch')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bankapp.district')),
            ],
        ),
    ]
