# Generated by Django 4.2.5 on 2023-09-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_remove_branch_dname_remove_district_dname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='form',
            name='materials_provided',
        ),
    ]
